-- One row per NCT ID per ingestion run. Dates parsed leniently (registry
-- dates may be partial); raw strings preserved alongside parsed values.
select
    ingestion_run_id,
    snapshot_id,
    timezone('UTC', try_cast(retrieved_at_utc as timestamptz)) as retrieved_at_utc,
    raw_page_reference,
    cast(raw_study_ordinal as bigint) as raw_study_ordinal,
    indication_profile_id,
    timezone('UTC', try_cast(snapshot_timestamp_utc as timestamptz)) as snapshot_timestamp_utc,
    cast(timezone('UTC', try_cast(snapshot_timestamp_utc as timestamptz)) as date) as snapshot_date,
    nct_id,
    brief_title,
    official_title,
    study_type,
    overall_status,
    last_known_status,
    status_verified_date as status_verified_date_raw,
    cast(expanded_access_info as boolean) as has_expanded_access,
    start_date as start_date_raw,
    {{ parse_partial_date('start_date') }} as start_date,
    primary_completion_date as primary_completion_date_raw,
    {{ parse_partial_date('primary_completion_date') }} as primary_completion_date,
    completion_date as completion_date_raw,
    {{ parse_partial_date('completion_date') }} as completion_date,
    study_first_post_date as study_first_post_date_raw,
    {{ parse_partial_date('study_first_post_date') }} as study_first_post_date,
    results_first_post_date as results_first_post_date_raw,
    {{ parse_partial_date('results_first_post_date') }} as results_first_post_date,
    last_update_post_date as last_update_post_date_raw,
    {{ parse_partial_date('last_update_post_date') }} as last_update_post_date,
    phase_raw,
    phase_normalized,
    try_cast(enrollment_count as integer) as enrollment_count,
    enrollment_type,
    allocation,
    primary_purpose,
    lead_sponsor_name,
    {{ normalize_text('lead_sponsor_name') }} as lead_sponsor_normalized,
    responsible_party_type,
    cast(healthy_volunteers as boolean) as healthy_volunteers,
    minimum_age,
    maximum_age,
    sex,
    eligibility_criteria_text,
    cast(has_results_flag as boolean) as has_results_flag,
    source_json_hash,
    record_quality_flag
from {{ source('silver', 'silver_trials') }}
where nct_id is not null
